id_to_name = {
    "T2_BAG": "Novice's Bag",
    "T3_BAG": "Journeyman's Bag",
    "T4_BAG": "Adept's Bag",
    "T4_BAG@1": "Adept's Bag",
    "T4_BAG@2": "Adept's Bag",
    "T4_BAG@3": "Adept's Bag",
    "T4_BAG@4": "Adept's Bag",
    "T5_BAG": "Expert's Bag",
    "T5_BAG@1": "Expert's Bag",
    "T5_BAG@2": "Expert's Bag",
    "T5_BAG@3": "Expert's Bag",
    "T5_BAG@4": "Expert's Bag",
    "T6_BAG": "Master's Bag",
    "T6_BAG@1": "Master's Bag",
    "T6_BAG@2": "Master's Bag",
    "T6_BAG@3": "Master's Bag",
    "T6_BAG@4": "Master's Bag",
    "T7_BAG": "Grandmaster's Bag",
    "T7_BAG@1": "Grandmaster's Bag",
    "T7_BAG@2": "Grandmaster's Bag",
    "T7_BAG@3": "Grandmaster's Bag",
    "T7_BAG@4": "Grandmaster's Bag",
    "T8_BAG": "Elder's Bag",
    "T8_BAG@1": "Elder's Bag",
    "T8_BAG@2": "Elder's Bag",
    "T8_BAG@3": "Elder's Bag",
    "T8_BAG@4": "Elder's Bag",
    "T4_BAG_INSIGHT": "Adept's Satchel of Insight",
    "T4_BAG_INSIGHT@1": "Adept's Satchel of Insight",
    "T4_BAG_INSIGHT@2": "Adept's Satchel of Insight",
    "T4_BAG_INSIGHT@3": "Adept's Satchel of Insight",
    "T4_BAG_INSIGHT@4": "Adept's Satchel of Insight",
    "T5_BAG_INSIGHT": "Expert's Satchel of Insight",
    "T5_BAG_INSIGHT@1": "Expert's Satchel of Insight",
    "T5_BAG_INSIGHT@2": "Expert's Satchel of Insight",
    "T5_BAG_INSIGHT@3": "Expert's Satchel of Insight",
    "T5_BAG_INSIGHT@4": "Expert's Satchel of Insight",
    "T6_BAG_INSIGHT": "Master's Satchel of Insight",
    "T6_BAG_INSIGHT@1": "Master's Satchel of Insight",
    "T6_BAG_INSIGHT@2": "Master's Satchel of Insight",
    "T6_BAG_INSIGHT@3": "Master's Satchel of Insight",
    "T6_BAG_INSIGHT@4": "Master's Satchel of Insight",
    "T7_BAG_INSIGHT": "Grandmaster's Satchel of Insight",
    "T7_BAG_INSIGHT@1": "Grandmaster's Satchel of Insight",
    "T7_BAG_INSIGHT@2": "Grandmaster's Satchel of Insight",
    "T7_BAG_INSIGHT@3": "Grandmaster's Satchel of Insight",
    "T7_BAG_INSIGHT@4": "Grandmaster's Satchel of Insight",
    "T8_BAG_INSIGHT": "Elder's Satchel of Insight",
    "T8_BAG_INSIGHT@1": "Elder's Satchel of Insight",
    "T8_BAG_INSIGHT@2": "Elder's Satchel of Insight",
    "T8_BAG_INSIGHT@3": "Elder's Satchel of Insight",
    "T8_BAG_INSIGHT@4": "Elder's Satchel of Insight",
    "T2_CAPE": "Novice's Cape",
    "T3_CAPE": "Journeyman's Cape",
    "T4_CAPE": "Adept's Cape",
    "T4_CAPE@1": "Adept's Cape",
    "T4_CAPE@2": "Adept's Cape",
    "T4_CAPE@3": "Adept's Cape",
    "T4_CAPE@4": "Adept's Cape",
    "T5_CAPE": "Expert's Cape",
    "T5_CAPE@1": "Expert's Cape",
    "T5_CAPE@2": "Expert's Cape",
    "T5_CAPE@3": "Expert's Cape",
    "T5_CAPE@4": "Expert's Cape",
    "T6_CAPE": "Master's Cape",
    "T6_CAPE@1": "Master's Cape",
    "T6_CAPE@2": "Master's Cape",
    "T6_CAPE@3": "Master's Cape",
    "T6_CAPE@4": "Master's Cape",
    "T7_CAPE": "Grandmaster's Cape",
    "T7_CAPE@1": "Grandmaster's Cape",
    "T7_CAPE@2": "Grandmaster's Cape",
    "T7_CAPE@3": "Grandmaster's Cape",
    "T7_CAPE@4": "Grandmaster's Cape",
    "T8_CAPE": "Elder's Cape",
    "T8_CAPE@1": "Elder's Cape",
    "T8_CAPE@2": "Elder's Cape",
    "T8_CAPE@3": "Elder's Cape",
    "T8_CAPE@4": "Elder's Cape",
    "T4_CAPEITEM_FW_BRIDGEWATCH": "Adept's Bridgewatch Cape",
    "T4_CAPEITEM_FW_BRIDGEWATCH@1": "Adept's Bridgewatch Cape",
    "T4_CAPEITEM_FW_BRIDGEWATCH@2": "Adept's Bridgewatch Cape",
    "T4_CAPEITEM_FW_BRIDGEWATCH@3": "Adept's Bridgewatch Cape",
    "T4_CAPEITEM_FW_BRIDGEWATCH@4": "Adept's Bridgewatch Cape",
    "T5_CAPEITEM_FW_BRIDGEWATCH": "Expert's Bridgewatch Cape",
    "T5_CAPEITEM_FW_BRIDGEWATCH@1": "Expert's Bridgewatch Cape",
    "T5_CAPEITEM_FW_BRIDGEWATCH@2": "Expert's Bridgewatch Cape",
    "T5_CAPEITEM_FW_BRIDGEWATCH@3": "Expert's Bridgewatch Cape",
    "T5_CAPEITEM_FW_BRIDGEWATCH@4": "Expert's Bridgewatch Cape",
    "T6_CAPEITEM_FW_BRIDGEWATCH": "Master's Bridgewatch Cape",
    "T6_CAPEITEM_FW_BRIDGEWATCH@1": "Master's Bridgewatch Cape",
    "T6_CAPEITEM_FW_BRIDGEWATCH@2": "Master's Bridgewatch Cape",
    "T6_CAPEITEM_FW_BRIDGEWATCH@3": "Master's Bridgewatch Cape",
    "T6_CAPEITEM_FW_BRIDGEWATCH@4": "Master's Bridgewatch Cape",
    "T7_CAPEITEM_FW_BRIDGEWATCH": "Grandmaster's Bridgewatch Cape",
    "T7_CAPEITEM_FW_BRIDGEWATCH@1": "Grandmaster's Bridgewatch Cape",
    "T7_CAPEITEM_FW_BRIDGEWATCH@2": "Grandmaster's Bridgewatch Cape",
    "T7_CAPEITEM_FW_BRIDGEWATCH@3": "Grandmaster's Bridgewatch Cape",
    "T7_CAPEITEM_FW_BRIDGEWATCH@4": "Grandmaster's Bridgewatch Cape",
    "T8_CAPEITEM_FW_BRIDGEWATCH": "Elder's Bridgewatch Cape",
    "T8_CAPEITEM_FW_BRIDGEWATCH@1": "Elder's Bridgewatch Cape",
    "T8_CAPEITEM_FW_BRIDGEWATCH@2": "Elder's Bridgewatch Cape",
    "T8_CAPEITEM_FW_BRIDGEWATCH@3": "Elder's Bridgewatch Cape",
    "T8_CAPEITEM_FW_BRIDGEWATCH@4": "Elder's Bridgewatch Cape",
    "T4_CAPEITEM_FW_FORTSTERLING": "Adept's Fort Sterling Cape",
    "T4_CAPEITEM_FW_FORTSTERLING@1": "Adept's Fort Sterling Cape",
    "T4_CAPEITEM_FW_FORTSTERLING@2": "Adept's Fort Sterling Cape",
    "T4_CAPEITEM_FW_FORTSTERLING@3": "Adept's Fort Sterling Cape",
    "T4_CAPEITEM_FW_FORTSTERLING@4": "Adept's Fort Sterling Cape",
    "T5_CAPEITEM_FW_FORTSTERLING": "Expert's Fort Sterling Cape",
    "T5_CAPEITEM_FW_FORTSTERLING@1": "Expert's Fort Sterling Cape",
    "T5_CAPEITEM_FW_FORTSTERLING@2": "Expert's Fort Sterling Cape",
    "T5_CAPEITEM_FW_FORTSTERLING@3": "Expert's Fort Sterling Cape",
    "T5_CAPEITEM_FW_FORTSTERLING@4": "Expert's Fort Sterling Cape",
    "T6_CAPEITEM_FW_FORTSTERLING": "Master's Fort Sterling Cape",
    "T6_CAPEITEM_FW_FORTSTERLING@1": "Master's Fort Sterling Cape",
    "T6_CAPEITEM_FW_FORTSTERLING@2": "Master's Fort Sterling Cape",
    "T6_CAPEITEM_FW_FORTSTERLING@3": "Master's Fort Sterling Cape",
    "T6_CAPEITEM_FW_FORTSTERLING@4": "Master's Fort Sterling Cape",
    "T7_CAPEITEM_FW_FORTSTERLING": "Grandmaster's Fort Sterling Cape",
    "T7_CAPEITEM_FW_FORTSTERLING@1": "Grandmaster's Fort Sterling Cape",
    "T7_CAPEITEM_FW_FORTSTERLING@2": "Grandmaster's Fort Sterling Cape",
    "T7_CAPEITEM_FW_FORTSTERLING@3": "Grandmaster's Fort Sterling Cape",
    "T7_CAPEITEM_FW_FORTSTERLING@4": "Grandmaster's Fort Sterling Cape",
    "T8_CAPEITEM_FW_FORTSTERLING": "Elder's Fort Sterling Cape",
    "T8_CAPEITEM_FW_FORTSTERLING@1": "Elder's Fort Sterling Cape",
    "T8_CAPEITEM_FW_FORTSTERLING@2": "Elder's Fort Sterling Cape",
    "T8_CAPEITEM_FW_FORTSTERLING@3": "Elder's Fort Sterling Cape",
    "T8_CAPEITEM_FW_FORTSTERLING@4": "Elder's Fort Sterling Cape",
    "T4_CAPEITEM_FW_LYMHURST": "Adept's Lymhurst Cape",
    "T4_CAPEITEM_FW_LYMHURST@1": "Adept's Lymhurst Cape",
    "T4_CAPEITEM_FW_LYMHURST@2": "Adept's Lymhurst Cape",
    "T4_CAPEITEM_FW_LYMHURST@3": "Adept's Lymhurst Cape",
    "T4_CAPEITEM_FW_LYMHURST@4": "Adept's Lymhurst Cape",
    "T5_CAPEITEM_FW_LYMHURST": "Expert's Lymhurst Cape",
    "T5_CAPEITEM_FW_LYMHURST@1": "Expert's Lymhurst Cape",
    "T5_CAPEITEM_FW_LYMHURST@2": "Expert's Lymhurst Cape",
    "T5_CAPEITEM_FW_LYMHURST@3": "Expert's Lymhurst Cape",
    "T5_CAPEITEM_FW_LYMHURST@4": "Expert's Lymhurst Cape",
    "T6_CAPEITEM_FW_LYMHURST": "Master's Lymhurst Cape",
    "T6_CAPEITEM_FW_LYMHURST@1": "Master's Lymhurst Cape",
    "T6_CAPEITEM_FW_LYMHURST@2": "Master's Lymhurst Cape",
    "T6_CAPEITEM_FW_LYMHURST@3": "Master's Lymhurst Cape",
    "T6_CAPEITEM_FW_LYMHURST@4": "Master's Lymhurst Cape",
    "T7_CAPEITEM_FW_LYMHURST": "Grandmaster's Lymhurst Cape",
    "T7_CAPEITEM_FW_LYMHURST@1": "Grandmaster's Lymhurst Cape",
    "T7_CAPEITEM_FW_LYMHURST@2": "Grandmaster's Lymhurst Cape",
    "T7_CAPEITEM_FW_LYMHURST@3": "Grandmaster's Lymhurst Cape",
    "T7_CAPEITEM_FW_LYMHURST@4": "Grandmaster's Lymhurst Cape",
    "T8_CAPEITEM_FW_LYMHURST": "Elder's Lymhurst Cape",
    "T8_CAPEITEM_FW_LYMHURST@1": "Elder's Lymhurst Cape",
    "T8_CAPEITEM_FW_LYMHURST@2": "Elder's Lymhurst Cape",
    "T8_CAPEITEM_FW_LYMHURST@3": "Elder's Lymhurst Cape",
    "T8_CAPEITEM_FW_LYMHURST@4": "Elder's Lymhurst Cape",
    "T4_CAPEITEM_FW_MARTLOCK": "Adept's Martlock Cape",
    "T4_CAPEITEM_FW_MARTLOCK@1": "Adept's Martlock Cape",
    "T4_CAPEITEM_FW_MARTLOCK@2": "Adept's Martlock Cape",
    "T4_CAPEITEM_FW_MARTLOCK@3": "Adept's Martlock Cape",
    "T4_CAPEITEM_FW_MARTLOCK@4": "Adept's Martlock Cape",
    "T5_CAPEITEM_FW_MARTLOCK": "Expert's Martlock Cape",
    "T5_CAPEITEM_FW_MARTLOCK@1": "Expert's Martlock Cape",
    "T5_CAPEITEM_FW_MARTLOCK@2": "Expert's Martlock Cape",
    "T5_CAPEITEM_FW_MARTLOCK@3": "Expert's Martlock Cape",
    "T5_CAPEITEM_FW_MARTLOCK@4": "Expert's Martlock Cape",
    "T6_CAPEITEM_FW_MARTLOCK": "Master's Martlock Cape",
    "T6_CAPEITEM_FW_MARTLOCK@1": "Master's Martlock Cape",
    "T6_CAPEITEM_FW_MARTLOCK@2": "Master's Martlock Cape",
    "T6_CAPEITEM_FW_MARTLOCK@3": "Master's Martlock Cape",
    "T6_CAPEITEM_FW_MARTLOCK@4": "Master's Martlock Cape",
    "T7_CAPEITEM_FW_MARTLOCK": "Grandmaster's Martlock Cape",
    "T7_CAPEITEM_FW_MARTLOCK@1": "Grandmaster's Martlock Cape",
    "T7_CAPEITEM_FW_MARTLOCK@2": "Grandmaster's Martlock Cape",
    "T7_CAPEITEM_FW_MARTLOCK@3": "Grandmaster's Martlock Cape",
    "T7_CAPEITEM_FW_MARTLOCK@4": "Grandmaster's Martlock Cape",
    "T8_CAPEITEM_FW_MARTLOCK": "Elder's Martlock Cape",
    "T8_CAPEITEM_FW_MARTLOCK@1": "Elder's Martlock Cape",
    "T8_CAPEITEM_FW_MARTLOCK@2": "Elder's Martlock Cape",
    "T8_CAPEITEM_FW_MARTLOCK@3": "Elder's Martlock Cape",
    "T8_CAPEITEM_FW_MARTLOCK@4": "Elder's Martlock Cape",
    "T4_CAPEITEM_FW_THETFORD": "Adept's Thetford Cape",
    "T4_CAPEITEM_FW_THETFORD@1": "Adept's Thetford Cape",
    "T4_CAPEITEM_FW_THETFORD@2": "Adept's Thetford Cape",
    "T4_CAPEITEM_FW_THETFORD@3": "Adept's Thetford Cape",
    "T4_CAPEITEM_FW_THETFORD@4": "Adept's Thetford Cape",
    "T5_CAPEITEM_FW_THETFORD": "Expert's Thetford Cape",
    "T5_CAPEITEM_FW_THETFORD@1": "Expert's Thetford Cape",
    "T5_CAPEITEM_FW_THETFORD@2": "Expert's Thetford Cape",
    "T5_CAPEITEM_FW_THETFORD@3": "Expert's Thetford Cape",
    "T5_CAPEITEM_FW_THETFORD@4": "Expert's Thetford Cape",
    "T6_CAPEITEM_FW_THETFORD": "Master's Thetford Cape",
    "T6_CAPEITEM_FW_THETFORD@1": "Master's Thetford Cape",
    "T6_CAPEITEM_FW_THETFORD@2": "Master's Thetford Cape",
    "T6_CAPEITEM_FW_THETFORD@3": "Master's Thetford Cape",
    "T6_CAPEITEM_FW_THETFORD@4": "Master's Thetford Cape",
    "T7_CAPEITEM_FW_THETFORD": "Grandmaster's Thetford Cape",
    "T7_CAPEITEM_FW_THETFORD@1": "Grandmaster's Thetford Cape",
    "T7_CAPEITEM_FW_THETFORD@2": "Grandmaster's Thetford Cape",
    "T7_CAPEITEM_FW_THETFORD@3": "Grandmaster's Thetford Cape",
    "T7_CAPEITEM_FW_THETFORD@4": "Grandmaster's Thetford Cape",
    "T8_CAPEITEM_FW_THETFORD": "Elder's Thetford Cape",
    "T8_CAPEITEM_FW_THETFORD@1": "Elder's Thetford Cape",
    "T8_CAPEITEM_FW_THETFORD@2": "Elder's Thetford Cape",
    "T8_CAPEITEM_FW_THETFORD@3": "Elder's Thetford Cape",
    "T8_CAPEITEM_FW_THETFORD@4": "Elder's Thetford Cape",
    "T4_CAPEITEM_FW_BRECILIEN": "Adept's Brecilien Cape",
    "T4_CAPEITEM_FW_BRECILIEN@1": "Adept's Brecilien Cape",
    "T4_CAPEITEM_FW_BRECILIEN@2": "Adept's Brecilien Cape",
    "T4_CAPEITEM_FW_BRECILIEN@3": "Adept's Brecilien Cape",
    "T4_CAPEITEM_FW_BRECILIEN@4": "Adept's Brecilien Cape",
    "T5_CAPEITEM_FW_BRECILIEN": "Expert's Brecilien Cape",
    "T5_CAPEITEM_FW_BRECILIEN@1": "Expert's Brecilien Cape",
    "T5_CAPEITEM_FW_BRECILIEN@2": "Expert's Brecilien Cape",
    "T5_CAPEITEM_FW_BRECILIEN@3": "Expert's Brecilien Cape",
    "T5_CAPEITEM_FW_BRECILIEN@4": "Expert's Brecilien Cape",
    "T6_CAPEITEM_FW_BRECILIEN": "Master's Brecilien Cape",
    "T6_CAPEITEM_FW_BRECILIEN@1": "Master's Brecilien Cape",
    "T6_CAPEITEM_FW_BRECILIEN@2": "Master's Brecilien Cape",
    "T6_CAPEITEM_FW_BRECILIEN@3": "Master's Brecilien Cape",
    "T6_CAPEITEM_FW_BRECILIEN@4": "Master's Brecilien Cape",
    "T7_CAPEITEM_FW_BRECILIEN": "Grandmaster's Brecilien Cape",
    "T7_CAPEITEM_FW_BRECILIEN@1": "Grandmaster's Brecilien Cape",
    "T7_CAPEITEM_FW_BRECILIEN@2": "Grandmaster's Brecilien Cape",
    "T7_CAPEITEM_FW_BRECILIEN@3": "Grandmaster's Brecilien Cape",
    "T7_CAPEITEM_FW_BRECILIEN@4": "Grandmaster's Brecilien Cape",
    "T8_CAPEITEM_FW_BRECILIEN": "Elder's Brecilien Cape",
    "T8_CAPEITEM_FW_BRECILIEN@1": "Elder's Brecilien Cape",
    "T8_CAPEITEM_FW_BRECILIEN@2": "Elder's Brecilien Cape",
    "T8_CAPEITEM_FW_BRECILIEN@3": "Elder's Brecilien Cape",
    "T8_CAPEITEM_FW_BRECILIEN@4": "Elder's Brecilien Cape",
    "T4_CAPEITEM_AVALON": "Adept's Avalonian Cape",
    "T4_CAPEITEM_AVALON@1": "Adept's Avalonian Cape",
    "T4_CAPEITEM_AVALON@2": "Adept's Avalonian Cape",
    "T4_CAPEITEM_AVALON@3": "Adept's Avalonian Cape",
    "T4_CAPEITEM_AVALON@4": "Adept's Avalonian Cape",
    "T5_CAPEITEM_AVALON": "Expert's Avalonian Cape",
    "T5_CAPEITEM_AVALON@1": "Expert's Avalonian Cape",
    "T5_CAPEITEM_AVALON@2": "Expert's Avalonian Cape",
    "T5_CAPEITEM_AVALON@3": "Expert's Avalonian Cape",
    "T5_CAPEITEM_AVALON@4": "Expert's Avalonian Cape",
    "T6_CAPEITEM_AVALON": "Master's Avalonian Cape",
    "T6_CAPEITEM_AVALON@1": "Master's Avalonian Cape",
    "T6_CAPEITEM_AVALON@2": "Master's Avalonian Cape",
    "T6_CAPEITEM_AVALON@3": "Master's Avalonian Cape",
    "T6_CAPEITEM_AVALON@4": "Master's Avalonian Cape",
    "T7_CAPEITEM_AVALON": "Grandmaster's Avalonian Cape",
    "T7_CAPEITEM_AVALON@1": "Grandmaster's Avalonian Cape",
    "T7_CAPEITEM_AVALON@2": "Grandmaster's Avalonian Cape",
    "T7_CAPEITEM_AVALON@3": "Grandmaster's Avalonian Cape",
    "T7_CAPEITEM_AVALON@4": "Grandmaster's Avalonian Cape",
    "T8_CAPEITEM_AVALON": "Elder's Avalonian Cape",
    "T8_CAPEITEM_AVALON@1": "Elder's Avalonian Cape",
    "T8_CAPEITEM_AVALON@2": "Elder's Avalonian Cape",
    "T8_CAPEITEM_AVALON@3": "Elder's Avalonian Cape",
    "T8_CAPEITEM_AVALON@4": "Elder's Avalonian Cape",
    "T4_CAPEITEM_HERETIC": "Adept's Heretic Cape",
    "T4_CAPEITEM_HERETIC@1": "Adept's Heretic Cape",
    "T4_CAPEITEM_HERETIC@2": "Adept's Heretic Cape",
    "T4_CAPEITEM_HERETIC@3": "Adept's Heretic Cape",
    "T4_CAPEITEM_HERETIC@4": "Adept's Heretic Cape",
    "T5_CAPEITEM_HERETIC": "Expert's Heretic Cape",
    "T5_CAPEITEM_HERETIC@1": "Expert's Heretic Cape",
    "T5_CAPEITEM_HERETIC@2": "Expert's Heretic Cape",
    "T5_CAPEITEM_HERETIC@3": "Expert's Heretic Cape",
    "T5_CAPEITEM_HERETIC@4": "Expert's Heretic Cape",
    "T6_CAPEITEM_HERETIC": "Master's Heretic Cape",
    "T6_CAPEITEM_HERETIC@1": "Master's Heretic Cape",
    "T6_CAPEITEM_HERETIC@2": "Master's Heretic Cape",
    "T6_CAPEITEM_HERETIC@3": "Master's Heretic Cape",
    "T6_CAPEITEM_HERETIC@4": "Master's Heretic Cape",
    "T7_CAPEITEM_HERETIC": "Grandmaster's Heretic Cape",
    "T7_CAPEITEM_HERETIC@1": "Grandmaster's Heretic Cape",
    "T7_CAPEITEM_HERETIC@2": "Grandmaster's Heretic Cape",
    "T7_CAPEITEM_HERETIC@3": "Grandmaster's Heretic Cape",
    "T7_CAPEITEM_HERETIC@4": "Grandmaster's Heretic Cape",
    "T8_CAPEITEM_HERETIC": "Elder's Heretic Cape",
    "T8_CAPEITEM_HERETIC@1": "Elder's Heretic Cape",
    "T8_CAPEITEM_HERETIC@2": "Elder's Heretic Cape",
    "T8_CAPEITEM_HERETIC@3": "Elder's Heretic Cape",
    "T8_CAPEITEM_HERETIC@4": "Elder's Heretic Cape",
    "T4_CAPEITEM_UNDEAD": "Adept's Undead Cape",
    "T4_CAPEITEM_UNDEAD@1": "Adept's Undead Cape",
    "T4_CAPEITEM_UNDEAD@2": "Adept's Undead Cape",
    "T4_CAPEITEM_UNDEAD@3": "Adept's Undead Cape",
    "T4_CAPEITEM_UNDEAD@4": "Adept's Undead Cape",
    "T5_CAPEITEM_UNDEAD": "Expert's Undead Cape",
    "T5_CAPEITEM_UNDEAD@1": "Expert's Undead Cape",
    "T5_CAPEITEM_UNDEAD@2": "Expert's Undead Cape",
    "T5_CAPEITEM_UNDEAD@3": "Expert's Undead Cape",
    "T5_CAPEITEM_UNDEAD@4": "Expert's Undead Cape",
    "T6_CAPEITEM_UNDEAD": "Master's Undead Cape",
    "T6_CAPEITEM_UNDEAD@1": "Master's Undead Cape",
    "T6_CAPEITEM_UNDEAD@2": "Master's Undead Cape",
    "T6_CAPEITEM_UNDEAD@3": "Master's Undead Cape",
    "T6_CAPEITEM_UNDEAD@4": "Master's Undead Cape",
    "T7_CAPEITEM_UNDEAD": "Grandmaster's Undead Cape",
    "T7_CAPEITEM_UNDEAD@1": "Grandmaster's Undead Cape",
    "T7_CAPEITEM_UNDEAD@2": "Grandmaster's Undead Cape",
    "T7_CAPEITEM_UNDEAD@3": "Grandmaster's Undead Cape",
    "T7_CAPEITEM_UNDEAD@4": "Grandmaster's Undead Cape",
    "T8_CAPEITEM_UNDEAD": "Elder's Undead Cape",
    "T8_CAPEITEM_UNDEAD@1": "Elder's Undead Cape",
    "T8_CAPEITEM_UNDEAD@2": "Elder's Undead Cape",
    "T8_CAPEITEM_UNDEAD@3": "Elder's Undead Cape",
    "T8_CAPEITEM_UNDEAD@4": "Elder's Undead Cape",
    "T4_CAPEITEM_KEEPER": "Adept's Keeper Cape",
    "T4_CAPEITEM_KEEPER@1": "Adept's Keeper Cape",
    "T4_CAPEITEM_KEEPER@2": "Adept's Keeper Cape",
    "T4_CAPEITEM_KEEPER@3": "Adept's Keeper Cape",
    "T4_CAPEITEM_KEEPER@4": "Adept's Keeper Cape",
    "T5_CAPEITEM_KEEPER": "Expert's Keeper Cape",
    "T5_CAPEITEM_KEEPER@1": "Expert's Keeper Cape",
    "T5_CAPEITEM_KEEPER@2": "Expert's Keeper Cape",
    "T5_CAPEITEM_KEEPER@3": "Expert's Keeper Cape",
    "T5_CAPEITEM_KEEPER@4": "Expert's Keeper Cape",
    "T6_CAPEITEM_KEEPER": "Master's Keeper Cape",
    "T6_CAPEITEM_KEEPER@1": "Master's Keeper Cape",
    "T6_CAPEITEM_KEEPER@2": "Master's Keeper Cape",
    "T6_CAPEITEM_KEEPER@3": "Master's Keeper Cape",
    "T6_CAPEITEM_KEEPER@4": "Master's Keeper Cape",
    "T7_CAPEITEM_KEEPER": "Grandmaster's Keeper Cape",
    "T7_CAPEITEM_KEEPER@1": "Grandmaster's Keeper Cape",
    "T7_CAPEITEM_KEEPER@2": "Grandmaster's Keeper Cape",
    "T7_CAPEITEM_KEEPER@3": "Grandmaster's Keeper Cape",
    "T7_CAPEITEM_KEEPER@4": "Grandmaster's Keeper Cape",
    "T8_CAPEITEM_KEEPER": "Elder's Keeper Cape",
    "T8_CAPEITEM_KEEPER@1": "Elder's Keeper Cape",
    "T8_CAPEITEM_KEEPER@2": "Elder's Keeper Cape",
    "T8_CAPEITEM_KEEPER@3": "Elder's Keeper Cape",
    "T8_CAPEITEM_KEEPER@4": "Elder's Keeper Cape",
    "T4_CAPEITEM_MORGANA": "Adept's Morgana Cape",
    "T4_CAPEITEM_MORGANA@1": "Adept's Morgana Cape",
    "T4_CAPEITEM_MORGANA@2": "Adept's Morgana Cape",
    "T4_CAPEITEM_MORGANA@3": "Adept's Morgana Cape",
    "T4_CAPEITEM_MORGANA@4": "Adept's Morgana Cape",
    "T5_CAPEITEM_MORGANA": "Expert's Morgana Cape",
    "T5_CAPEITEM_MORGANA@1": "Expert's Morgana Cape",
    "T5_CAPEITEM_MORGANA@2": "Expert's Morgana Cape",
    "T5_CAPEITEM_MORGANA@3": "Expert's Morgana Cape",
    "T5_CAPEITEM_MORGANA@4": "Expert's Morgana Cape",
    "T6_CAPEITEM_MORGANA": "Master's Morgana Cape",
    "T6_CAPEITEM_MORGANA@1": "Master's Morgana Cape",
    "T6_CAPEITEM_MORGANA@2": "Master's Morgana Cape",
    "T6_CAPEITEM_MORGANA@3": "Master's Morgana Cape",
    "T6_CAPEITEM_MORGANA@4": "Master's Morgana Cape",
    "T7_CAPEITEM_MORGANA": "Grandmaster's Morgana Cape",
    "T7_CAPEITEM_MORGANA@1": "Grandmaster's Morgana Cape",
    "T7_CAPEITEM_MORGANA@2": "Grandmaster's Morgana Cape",
    "T7_CAPEITEM_MORGANA@3": "Grandmaster's Morgana Cape",
    "T7_CAPEITEM_MORGANA@4": "Grandmaster's Morgana Cape",
    "T8_CAPEITEM_MORGANA": "Elder's Morgana Cape",
    "T8_CAPEITEM_MORGANA@1": "Elder's Morgana Cape",
    "T8_CAPEITEM_MORGANA@2": "Elder's Morgana Cape",
    "T8_CAPEITEM_MORGANA@3": "Elder's Morgana Cape",
    "T8_CAPEITEM_MORGANA@4": "Elder's Morgana Cape",
    "T4_CAPEITEM_DEMON": "Adept's Demon Cape",
    "T4_CAPEITEM_DEMON@1": "Adept's Demon Cape",
    "T4_CAPEITEM_DEMON@2": "Adept's Demon Cape",
    "T4_CAPEITEM_DEMON@3": "Adept's Demon Cape",
    "T4_CAPEITEM_DEMON@4": "Adept's Demon Cape",
    "T5_CAPEITEM_DEMON": "Expert's Demon Cape",
    "T5_CAPEITEM_DEMON@1": "Expert's Demon Cape",
    "T5_CAPEITEM_DEMON@2": "Expert's Demon Cape",
    "T5_CAPEITEM_DEMON@3": "Expert's Demon Cape",
    "T5_CAPEITEM_DEMON@4": "Expert's Demon Cape",
    "T6_CAPEITEM_DEMON": "Master's Demon Cape",
    "T6_CAPEITEM_DEMON@1": "Master's Demon Cape",
    "T6_CAPEITEM_DEMON@2": "Master's Demon Cape",
    "T6_CAPEITEM_DEMON@3": "Master's Demon Cape",
    "T6_CAPEITEM_DEMON@4": "Master's Demon Cape",
    "T7_CAPEITEM_DEMON": "Grandmaster's Demon Cape",
    "T7_CAPEITEM_DEMON@1": "Grandmaster's Demon Cape",
    "T7_CAPEITEM_DEMON@2": "Grandmaster's Demon Cape",
    "T7_CAPEITEM_DEMON@3": "Grandmaster's Demon Cape",
    "T7_CAPEITEM_DEMON@4": "Grandmaster's Demon Cape",
    "T8_CAPEITEM_DEMON": "Elder's Demon Cape",
    "T8_CAPEITEM_DEMON@1": "Elder's Demon Cape",
    "T8_CAPEITEM_DEMON@2": "Elder's Demon Cape",
    "T8_CAPEITEM_DEMON@3": "Elder's Demon Cape",
    "T8_CAPEITEM_DEMON@4": "Elder's Demon Cape",
    "T2_ARMOR_CLOTH_SET1": "Novice's Scholar Robe",
    "T3_ARMOR_CLOTH_SET1": "Journeyman's Scholar Robe",
    "T4_ARMOR_CLOTH_SET1": "Adept's Scholar Robe",
    "T5_ARMOR_CLOTH_SET1": "Expert's Scholar Robe",
    "T6_ARMOR_CLOTH_SET1": "Master's Scholar Robe",
    "T7_ARMOR_CLOTH_SET1": "Grandmaster's Scholar Robe",
    "T8_ARMOR_CLOTH_SET1": "Elder's Scholar Robe",
    "T4_ARMOR_CLOTH_SET2": "Adept's Cleric Robe",
    "T5_ARMOR_CLOTH_SET2": "Expert's Cleric Robe",
    "T6_ARMOR_CLOTH_SET2": "Master's Cleric Robe",
    "T7_ARMOR_CLOTH_SET2": "Grandmaster's Cleric Robe",
    "T8_ARMOR_CLOTH_SET2": "Elder's Cleric Robe",
    "T4_ARMOR_CLOTH_SET3": "Adept's Mage Robe",
    "T5_ARMOR_CLOTH_SET3": "Expert's Mage Robe",
    "T6_ARMOR_CLOTH_SET3": "Master's Mage Robe",
    "T7_ARMOR_CLOTH_SET3": "Grandmaster's Mage Robe",
    "T8_ARMOR_CLOTH_SET3": "Elder's Mage Robe",
    "T4_ARMOR_CLOTH_KEEPER": "Adept's Druid Robe",
    "T5_ARMOR_CLOTH_KEEPER": "Expert's Druid Robe",
    "T6_ARMOR_CLOTH_KEEPER": "Master's Druid Robe",
    "T7_ARMOR_CLOTH_KEEPER": "Grandmaster's Druid Robe",
    "T8_ARMOR_CLOTH_KEEPER": "Elder's Druid Robe",
    "T4_ARMOR_CLOTH_HELL": "Adept's Fiend Robe",
    "T5_ARMOR_CLOTH_HELL": "Expert's Fiend Robe",
    "T6_ARMOR_CLOTH_HELL": "Master's Fiend Robe",
    "T7_ARMOR_CLOTH_HELL": "Grandmaster's Fiend Robe",
    "T8_ARMOR_CLOTH_HELL": "Elder's Fiend Robe",
    "T4_ARMOR_CLOTH_MORGANA": "Adept's Cultist Robe",
    "T5_ARMOR_CLOTH_MORGANA": "Expert's Cultist Robe",
    "T6_ARMOR_CLOTH_MORGANA": "Master's Cultist Robe",
    "T7_ARMOR_CLOTH_MORGANA": "Grandmaster's Cultist Robe",
    "T8_ARMOR_CLOTH_MORGANA": "Elder's Cultist Robe",
    "T4_ARMOR_CLOTH_ROYAL": "Adept's Royal Robe",
    "T5_ARMOR_CLOTH_ROYAL": "Expert's Royal Robe",
    "T6_ARMOR_CLOTH_ROYAL": "Master's Royal Robe",
    "T7_ARMOR_CLOTH_ROYAL": "Grandmaster's Royal Robe",
    "T8_ARMOR_CLOTH_ROYAL": "Elder's Royal Robe",
    "T4_ARMOR_CLOTH_FEY": "Adept's Feyscale Robe",
    "T5_ARMOR_CLOTH_FEY": "Expert's Feyscale Robe",
    "T6_ARMOR_CLOTH_FEY": "Master's Feyscale Robe",
    "T7_ARMOR_CLOTH_FEY": "Grandmaster's Feyscale Robe",
    "T8_ARMOR_CLOTH_FEY": "Elder's Feyscale Robe",
    "T4_ARMOR_CLOTH_AVALON": "Adept's Robe of Purity",
    "T5_ARMOR_CLOTH_AVALON": "Expert's Robe of Purity",
    "T6_ARMOR_CLOTH_AVALON": "Master's Robe of Purity",
    "T7_ARMOR_CLOTH_AVALON": "Grandmaster's Robe of Purity",
    "T8_ARMOR_CLOTH_AVALON": "Elder's Robe of Purity",
    "T2_HEAD_CLOTH_SET1": "Novice's Scholar Cowl",
    "T3_HEAD_CLOTH_SET1": "Journeyman's Scholar Cowl",
    "T4_HEAD_CLOTH_SET1": "Adept's Scholar Cowl",
    "T5_HEAD_CLOTH_SET1": "Expert's Scholar Cowl",
    "T6_HEAD_CLOTH_SET1": "Master's Scholar Cowl",
    "T7_HEAD_CLOTH_SET1": "Grandmaster's Scholar Cowl",
    "T8_HEAD_CLOTH_SET1": "Elder's Scholar Cowl",
    "T4_HEAD_CLOTH_SET2": "Adept's Cleric Cowl",
    "T5_HEAD_CLOTH_SET2": "Expert's Cleric Cowl",
    "T6_HEAD_CLOTH_SET2": "Master's Cleric Cowl",
    "T7_HEAD_CLOTH_SET2": "Grandmaster's Cleric Cowl",
    "T8_HEAD_CLOTH_SET2": "Elder's Cleric Cowl",
    "T4_HEAD_CLOTH_SET3": "Adept's Mage Cowl",
    "T5_HEAD_CLOTH_SET3": "Expert's Mage Cowl",
    "T6_HEAD_CLOTH_SET3": "Master's Mage Cowl",
    "T7_HEAD_CLOTH_SET3": "Grandmaster's Mage Cowl",
    "T8_HEAD_CLOTH_SET3": "Elder's Mage Cowl",
    "T4_HEAD_CLOTH_KEEPER": "Adept's Druid Cowl",
    "T5_HEAD_CLOTH_KEEPER": "Expert's Druid Cowl",
    "T6_HEAD_CLOTH_KEEPER": "Master's Druid Cowl",
    "T7_HEAD_CLOTH_KEEPER": "Grandmaster's Druid Cowl",
    "T8_HEAD_CLOTH_KEEPER": "Elder's Druid Cowl",
    "T4_HEAD_CLOTH_ROYAL": "Adept's Royal Cowl",
    "T5_HEAD_CLOTH_ROYAL": "Expert's Royal Cowl",
    "T6_HEAD_CLOTH_ROYAL": "Master's Royal Cowl",
    "T7_HEAD_CLOTH_ROYAL": "Grandmaster's Royal Cowl",
    "T8_HEAD_CLOTH_ROYAL": "Elder's Royal Cowl",
    "T4_HEAD_CLOTH_FEY": "Adept's Feyscale Hat",
    "T5_HEAD_CLOTH_FEY": "Expert's Feyscale Hat",
    "T6_HEAD_CLOTH_FEY": "Master's Feyscale Hat",
    "T7_HEAD_CLOTH_FEY": "Grandmaster's Feyscale Hat",
    "T8_HEAD_CLOTH_FEY": "Elder's Feyscale Hat",
    "T4_HEAD_CLOTH_AVALON": "Adept's Cowl of Purity",
    "T5_HEAD_CLOTH_AVALON": "Expert's Cowl of Purity",
    "T6_HEAD_CLOTH_AVALON": "Master's Cowl of Purity",
    "T7_HEAD_CLOTH_AVALON": "Grandmaster's Cowl of Purity",
    "T8_HEAD_CLOTH_AVALON": "Elder's Cowl of Purity",
    "T4_HEAD_CLOTH_HELL": "Adept's Fiend Cowl",
    "T5_HEAD_CLOTH_HELL": "Expert's Fiend Cowl",
    "T6_HEAD_CLOTH_HELL": "Master's Fiend Cowl",
    "T7_HEAD_CLOTH_HELL": "Grandmaster's Fiend Cowl",
    "T8_HEAD_CLOTH_HELL": "Elder's Fiend Cowl",
    "T4_HEAD_CLOTH_MORGANA": "Adept's Cultist Cowl",
    "T5_HEAD_CLOTH_MORGANA": "Expert's Cultist Cowl",
    "T6_HEAD_CLOTH_MORGANA": "Master's Cultist Cowl",
    "T7_HEAD_CLOTH_MORGANA": "Grandmaster's Cultist Cowl",
    "T8_HEAD_CLOTH_MORGANA": "Elder's Cultist Cowl",
    "T2_ARMOR_LEATHER_SET1": "Novice's Mercenary Jacket",
    "T3_ARMOR_LEATHER_SET1": "Journeyman's Mercenary Jacket",
    "T4_ARMOR_LEATHER_SET1": "Adept's Mercenary Jacket",
    "T5_ARMOR_LEATHER_SET1": "Expert's Mercenary Jacket",
    "T6_ARMOR_LEATHER_SET1": "Master's Mercenary Jacket",
    "T7_ARMOR_LEATHER_SET1": "Grandmaster's Mercenary Jacket",
    "T8_ARMOR_LEATHER_SET1": "Elder's Mercenary Jacket",
    "T4_ARMOR_LEATHER_SET2": "Adept's Hunter Jacket",
    "T5_ARMOR_LEATHER_SET2": "Expert's Hunter Jacket",
    "T6_ARMOR_LEATHER_SET2": "Master's Hunter Jacket",
    "T7_ARMOR_LEATHER_SET2": "Grandmaster's Hunter Jacket",
    "T8_ARMOR_LEATHER_SET2": "Elder's Hunter Jacket",
    "T4_ARMOR_LEATHER_SET3": "Adept's Assassin Jacket",
    "T5_ARMOR_LEATHER_SET3": "Expert's Assassin Jacket",
    "T6_ARMOR_LEATHER_SET3": "Master's Assassin Jacket",
    "T7_ARMOR_LEATHER_SET3": "Grandmaster's Assassin Jacket",
    "T8_ARMOR_LEATHER_SET3": "Elder's Assassin Jacket",
    "T4_ARMOR_LEATHER_HELL": "Adept's Hellion Jacket",
    "T5_ARMOR_LEATHER_HELL": "Expert's Hellion Jacket",
    "T6_ARMOR_LEATHER_HELL": "Master's Hellion Jacket",
    "T7_ARMOR_LEATHER_HELL": "Grandmaster's Hellion Jacket",
    "T8_ARMOR_LEATHER_HELL": "Elder's Hellion Jacket",
    "T4_ARMOR_LEATHER_MORGANA": "Adept's Stalker Jacket",
    "T5_ARMOR_LEATHER_MORGANA": "Expert's Stalker Jacket",
    "T6_ARMOR_LEATHER_MORGANA": "Master's Stalker Jacket",
    "T7_ARMOR_LEATHER_MORGANA": "Grandmaster's Stalker Jacket",
    "T8_ARMOR_LEATHER_MORGANA": "Elder's Stalker Jacket",
    "T4_ARMOR_LEATHER_ROYAL": "Adept's Royal Jacket",
    "T5_ARMOR_LEATHER_ROYAL": "Expert's Royal Jacket",
    "T6_ARMOR_LEATHER_ROYAL": "Master's Royal Jacket",
    "T7_ARMOR_LEATHER_ROYAL": "Grandmaster's Royal Jacket",
    "T8_ARMOR_LEATHER_ROYAL": "Elder's Royal Jacket",
    "T4_ARMOR_LEATHER_FEY": "Adept's Mistwalker Jacket",
    "T5_ARMOR_LEATHER_FEY": "Expert's Mistwalker Jacket",
    "T6_ARMOR_LEATHER_FEY": "Master's Mistwalker Jacket",
    "T7_ARMOR_LEATHER_FEY": "Grandmaster's Mistwalker Jacket",
    "T8_ARMOR_LEATHER_FEY": "Elder's Mistwalker Jacket",
    "T4_ARMOR_LEATHER_AVALON": "Adept's Jacket of Tenacity",
    "T5_ARMOR_LEATHER_AVALON": "Expert's Jacket of Tenacity",
    "T6_ARMOR_LEATHER_AVALON": "Master's Jacket of Tenacity",
    "T7_ARMOR_LEATHER_AVALON": "Grandmaster's Jacket of Tenacity",
    "T8_ARMOR_LEATHER_AVALON": "Elder's Jacket of Tenacity",
    "T2_HEAD_LEATHER_SET1": "Novice's Mercenary Hood",
    "T3_HEAD_LEATHER_SET1": "Journeyman's Mercenary Hood",
    "T4_HEAD_LEATHER_SET1": "Adept's Mercenary Hood",
    "T5_HEAD_LEATHER_SET1": "Expert's Mercenary Hood",
    "T6_HEAD_LEATHER_SET1": "Master's Mercenary Hood",
    "T7_HEAD_LEATHER_SET1": "Grandmaster's Mercenary Hood",
    "T8_HEAD_LEATHER_SET1": "Elder's Mercenary Hood",
    "T4_HEAD_LEATHER_SET2": "Adept's Hunter Hood",
    "T5_HEAD_LEATHER_SET2": "Expert's Hunter Hood",
    "T6_HEAD_LEATHER_SET2": "Master's Hunter Hood",
    "T7_HEAD_LEATHER_SET2": "Grandmaster's Hunter Hood",
    "T8_HEAD_LEATHER_SET2": "Elder's Hunter Hood",
    "T4_HEAD_LEATHER_SET3": "Adept's Assassin Hood",
    "T5_HEAD_LEATHER_SET3": "Expert's Assassin Hood",
    "T6_HEAD_LEATHER_SET3": "Master's Assassin Hood",
    "T7_HEAD_LEATHER_SET3": "Grandmaster's Assassin Hood",
    "T8_HEAD_LEATHER_SET3": "Elder's Assassin Hood",
    "T4_HEAD_LEATHER_ROYAL": "Adept's Royal Hood",
    "T5_HEAD_LEATHER_ROYAL": "Expert's Royal Hood",
    "T6_HEAD_LEATHER_ROYAL": "Master's Royal Hood",
    "T7_HEAD_LEATHER_ROYAL": "Grandmaster's Royal Hood",
    "T8_HEAD_LEATHER_ROYAL": "Elder's Royal Hood",
    "T4_HEAD_LEATHER_FEY": "Adept's Mistwalker Hood",
    "T5_HEAD_LEATHER_FEY": "Expert's Mistwalker Hood",
    "T6_HEAD_LEATHER_FEY": "Master's Mistwalker Hood",
    "T7_HEAD_LEATHER_FEY": "Grandmaster's Mistwalker Hood",
    "T8_HEAD_LEATHER_FEY": "Elder's Mistwalker Hood",
    "T4_HEAD_LEATHER_AVALON": "Adept's Hood of Tenacity",
    "T5_HEAD_LEATHER_AVALON": "Expert's Hood of Tenacity",
    "T6_HEAD_LEATHER_AVALON": "Master's Hood of Tenacity",
    "T7_HEAD_LEATHER_AVALON": "Grandmaster's Hood of Tenacity",
    "T8_HEAD_LEATHER_AVALON": "Elder's Hood of Tenacity",
    "T4_HEAD_LEATHER_HELL": "Adept's Hellion Hood",
    "T5_HEAD_LEATHER_HELL": "Expert's Hellion Hood",
    "T6_HEAD_LEATHER_HELL": "Master's Hellion Hood",
    "T7_HEAD_LEATHER_HELL": "Grandmaster's Hellion Hood",
    "T8_HEAD_LEATHER_HELL": "Elder's Hellion Hood",
    "T4_HEAD_LEATHER_MORGANA": "Adept's Stalker Hood",
    "T5_HEAD_LEATHER_MORGANA": "Expert's Stalker Hood",
    "T6_HEAD_LEATHER_MORGANA": "Master's Stalker Hood",
    "T7_HEAD_LEATHER_MORGANA": "Grandmaster's Stalker Hood",
    "T8_HEAD_LEATHER_MORGANA": "Elder's Stalker Hood",
    "T2_ARMOR_PLATE_SET1": "Novice's Soldier Armor",
    "T3_ARMOR_PLATE_SET1": "Journeyman's Soldier Armor",
    "T4_ARMOR_PLATE_SET1": "Adept's Soldier Armor",
    "T5_ARMOR_PLATE_SET1": "Expert's Soldier Armor",
    "T6_ARMOR_PLATE_SET1": "Master's Soldier Armor",
    "T7_ARMOR_PLATE_SET1": "Grandmaster's Soldier Armor",
    "T8_ARMOR_PLATE_SET1": "Elder's Soldier Armor",
    "T4_ARMOR_PLATE_SET2": "Adept's Knight Armor",
    "T5_ARMOR_PLATE_SET2": "Expert's Knight Armor",
    "T6_ARMOR_PLATE_SET2": "Master's Knight Armor",
    "T7_ARMOR_PLATE_SET2": "Grandmaster's Knight Armor",
    "T8_ARMOR_PLATE_SET2": "Elder's Knight Armor",
    "T4_ARMOR_PLATE_SET3": "Adept's Guardian Armor",
    "T5_ARMOR_PLATE_SET3": "Expert's Guardian Armor",
    "T6_ARMOR_PLATE_SET3": "Master's Guardian Armor",
    "T7_ARMOR_PLATE_SET3": "Grandmaster's Guardian Armor",
    "T8_ARMOR_PLATE_SET3": "Elder's Guardian Armor",
    "T4_ARMOR_PLATE_KEEPER": "Adept's Judicator Armor",
    "T5_ARMOR_PLATE_KEEPER": "Expert's Judicator Armor",
    "T6_ARMOR_PLATE_KEEPER": "Master's Judicator Armor",
    "T7_ARMOR_PLATE_KEEPER": "Grandmaster's Judicator Armor",
    "T8_ARMOR_PLATE_KEEPER": "Elder's Judicator Armor",
    "T4_ARMOR_PLATE_HELL": "Adept's Demon Armor",
    "T5_ARMOR_PLATE_HELL": "Expert's Demon Armor",
    "T6_ARMOR_PLATE_HELL": "Master's Demon Armor",
    "T7_ARMOR_PLATE_HELL": "Grandmaster's Demon Armor",
    "T8_ARMOR_PLATE_HELL": "Elder's Demon Armor",
    "T4_ARMOR_PLATE_ROYAL": "Adept's Royal Armor",
    "T5_ARMOR_PLATE_ROYAL": "Expert's Royal Armor",
    "T6_ARMOR_PLATE_ROYAL": "Master's Royal Armor",
    "T7_ARMOR_PLATE_ROYAL": "Grandmaster's Royal Armor",
    "T8_ARMOR_PLATE_ROYAL": "Elder's Royal Armor",
    "T4_ARMOR_PLATE_FEY": "Adept's Duskweaver Armor",
    "T5_ARMOR_PLATE_FEY": "Expert's Duskweaver Armor",
    "T6_ARMOR_PLATE_FEY": "Master's Duskweaver Armor",
    "T7_ARMOR_PLATE_FEY": "Grandmaster's Duskweaver Armor",
    "T8_ARMOR_PLATE_FEY": "Elder's Duskweaver Armor",
    "T4_ARMOR_PLATE_AVALON": "Adept's Armor of Valor",
    "T5_ARMOR_PLATE_AVALON": "Expert's Armor of Valor",
    "T6_ARMOR_PLATE_AVALON": "Master's Armor of Valor",
    "T7_ARMOR_PLATE_AVALON": "Grandmaster's Armor of Valor",
    "T8_ARMOR_PLATE_AVALON": "Elder's Armor of Valor",
    "T2_HEAD_PLATE_SET1": "Novice's Soldier Helmet",
    "T3_HEAD_PLATE_SET1": "Journeyman's Soldier Helmet",
    "T4_HEAD_PLATE_SET1": "Adept's Soldier Helmet",
    "T5_HEAD_PLATE_SET1": "Expert's Soldier Helmet",
    "T6_HEAD_PLATE_SET1": "Master's Soldier Helmet",
    "T7_HEAD_PLATE_SET1": "Grandmaster's Soldier Helmet",
    "T8_HEAD_PLATE_SET1": "Elder's Soldier Helmet",
    "T4_HEAD_PLATE_SET2": "Adept's Knight Helmet",
    "T5_HEAD_PLATE_SET2": "Expert's Knight Helmet",
    "T6_HEAD_PLATE_SET2": "Master's Knight Helmet",
    "T7_HEAD_PLATE_SET2": "Grandmaster's Knight Helmet",
    "T8_HEAD_PLATE_SET2": "Elder's Knight Helmet",
    "T4_HEAD_PLATE_SET3": "Adept's Guardian Helmet",
    "T5_HEAD_PLATE_SET3": "Expert's Guardian Helmet",
    "T6_HEAD_PLATE_SET3": "Master's Guardian Helmet",
    "T7_HEAD_PLATE_SET3": "Grandmaster's Guardian Helmet",
    "T8_HEAD_PLATE_SET3": "Elder's Guardian Helmet",
    "T4_HEAD_PLATE_KEEPER": "Adept's Judicator Helmet",
    "T5_HEAD_PLATE_KEEPER": "Expert's Judicator Helmet",
    "T6_HEAD_PLATE_KEEPER": "Master's Judicator Helmet",
    "T7_HEAD_PLATE_KEEPER": "Grandmaster's Judicator Helmet",
    "T8_HEAD_PLATE_KEEPER": "Elder's Judicator Helmet",
    "T4_HEAD_PLATE_ROYAL": "Adept's Royal Helmet",
    "T5_HEAD_PLATE_ROYAL": "Expert's Royal Helmet",
    "T6_HEAD_PLATE_ROYAL": "Master's Royal Helmet",
    "T7_HEAD_PLATE_ROYAL": "Grandmaster's Royal Helmet",
    "T8_HEAD_PLATE_ROYAL": "Elder's Royal Helmet",
    "T4_HEAD_PLATE_FEY": "Adept's Duskweaver Helmet",
    "T5_HEAD_PLATE_FEY": "Expert's Duskweaver Helmet",
    "T6_HEAD_PLATE_FEY": "Master's Duskweaver Helmet",
    "T7_HEAD_PLATE_FEY": "Grandmaster's Duskweaver Helmet",
    "T8_HEAD_PLATE_FEY": "Elder's Duskweaver Helmet",
    "T4_HEAD_PLATE_AVALON": "Adept's Helmet of Valor",
    "T5_HEAD_PLATE_AVALON": "Expert's Helmet of Valor",
    "T6_HEAD_PLATE_AVALON": "Master's Helmet of Valor",
    "T7_HEAD_PLATE_AVALON": "Grandmaster's Helmet of Valor",
    "T8_HEAD_PLATE_AVALON": "Elder's Helmet of Valor",
    "T4_HEAD_PLATE_HELL": "Adept's Demon Helmet",
    "T5_HEAD_PLATE_HELL": "Expert's Demon Helmet",
    "T6_HEAD_PLATE_HELL": "Master's Demon Helmet",
    "T7_HEAD_PLATE_HELL": "Grandmaster's Demon Helmet",
    "T8_HEAD_PLATE_HELL": "Elder's Demon Helmet",
}